/*** Autogenerated by WIDL 6.0.3 from RPCInterface/meathook_interface.idl - Do not edit ***/
#include <string.h>

#include "meathook_interface.h"

#ifndef DECLSPEC_HIDDEN
#define DECLSPEC_HIDDEN
#endif

#define TYPE_FORMAT_STRING_SIZE 387
#define PROC_FORMAT_STRING_SIZE 597

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

/*****************************************************************************
 * meathook_interface interface
 */

static RPC_DISPATCH_TABLE meathook_interface_v1_0_DispatchTable;
static const MIDL_SERVER_INFO meathook_interface_ServerInfo;

static const RPC_SERVER_INTERFACE meathook_interface___RpcServerInterface =
{
    sizeof(RPC_SERVER_INTERFACE),
    {{0x1c9ca7c8,0xd421,0x482d,{0xb8,0x5d,0x79,0xfa,0xc3,0x3b,0x26,0x58}},{1,0}},
    {{0x8a885d04,0x1ceb,0x11c9,{0x9f,0xe8,0x08,0x00,0x2b,0x10,0x48,0x60}},{2,0}},
    &meathook_interface_v1_0_DispatchTable,
    0,
    0,
    0,
    &meathook_interface_ServerInfo,
    0,
};
RPC_IF_HANDLE meathook_interface_v1_0_s_ifspec DECLSPEC_HIDDEN = (RPC_IF_HANDLE)& meathook_interface___RpcServerInterface;

static const MIDL_STUB_DESC meathook_interface_StubDesc;

#if !defined(__RPC_WIN64__)
#error  Invalid build platform for this stub.
#endif

static const unsigned short meathook_interface_FormatStringOffsetTable[] =
{
    0,  /* ExecuteConsoleCommand */
    32,  /* PushEntitiesFile */
    76,  /* UploadData */
    120,  /* GetEntitiesFile */
    158,  /* GetActiveEncounter */
    196,  /* GetCurrentCheckpoint */
    234,  /* GetSpawnInfo */
    272,  /* KeepAlive */
    304,  /* GetAPRuntimeInfo */
    336,  /* GetRuntimeSnapshot */
    368,  /* ApplyDeathLink */
    406,  /* GetAPEventsSince */
    450,  /* GetInventoryItemCount */
    488,  /* HasPlayerPerk */
    526,  /* IsPlayerPerkActive */
    564,  /* GetEquippedWeapon */
};

static const MIDL_STUB_DESC meathook_interface_StubDesc =
{
    (void *)& meathook_interface___RpcServerInterface,
    MIDL_user_allocate,
    MIDL_user_free,
    {
        0,
    },
    0,
    0,
    0,
    0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

static RPC_DISPATCH_FUNCTION meathook_interface_table[] =
{
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    0
};
static RPC_DISPATCH_TABLE meathook_interface_v1_0_DispatchTable =
{
    16,
    meathook_interface_table
};

static const SERVER_ROUTINE meathook_interface_ServerRoutineTable[] =
{
    (void *)ExecuteConsoleCommand,
    (void *)PushEntitiesFile,
    (void *)UploadData,
    (void *)GetEntitiesFile,
    (void *)GetActiveEncounter,
    (void *)GetCurrentCheckpoint,
    (void *)GetSpawnInfo,
    (void *)KeepAlive,
    (void *)GetAPRuntimeInfo,
    (void *)GetRuntimeSnapshot,
    (void *)ApplyDeathLink,
    (void *)GetAPEventsSince,
    (void *)GetInventoryItemCount,
    (void *)HasPlayerPerk,
    (void *)IsPlayerPerkActive,
    (void *)GetEquippedWeapon,
};

static const MIDL_SERVER_INFO meathook_interface_ServerInfo =
{
    &meathook_interface_StubDesc,
    meathook_interface_ServerRoutineTable,
    __MIDL_ProcFormatString.Format,
    meathook_interface_FormatStringOffsetTable,
    0,
    0,
    0,
    0
};

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure meathook_interface::ExecuteConsoleCommand) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x0),	/* method 0 */
        NdrFcShort(0x8),	/* stack size = 8 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x0),	/* server buffer = 0 */
        0x42,
        0x01,	/* 1 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 26 (parameter pszString) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x4),	/* type offset = 4 */
/* 32 (procedure meathook_interface::PushEntitiesFile) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x1),	/* method 1 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0xd),	/* client buffer = 13 */
        NdrFcShort(0x0),	/* server buffer = 0 */
        0x42,
        0x03,	/* 3 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 58 (parameter pBuffer) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x8),	/* type offset = 8 */
/* 64 (parameter Start) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x02,	/* FC_CHAR */
        0x0,
/* 70 (parameter Size) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 76 (procedure meathook_interface::UploadData) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x2),	/* method 2 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x0),	/* server buffer = 0 */
        0x42,
        0x03,	/* 3 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 102 (parameter Size) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 108 (parameter Offset) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 114 (parameter pBuffer) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0xa),	/* type offset = 10 */
/* 120 (procedure meathook_interface::GetEntitiesFile) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x41,
        0x02,	/* 2 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 146 (parameter Size) */
        NdrFcShort(0x158),	/* flags: in, out, base type, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 152 (parameter pBuffer) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x1c),	/* type offset = 28 */
/* 158 (procedure meathook_interface::GetActiveEncounter) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x41,
        0x02,	/* 2 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 184 (parameter Size) */
        NdrFcShort(0x158),	/* flags: in, out, base type, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 190 (parameter pBuffer) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x2e),	/* type offset = 46 */
/* 196 (procedure meathook_interface::GetCurrentCheckpoint) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x41,
        0x02,	/* 2 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 222 (parameter Size) */
        NdrFcShort(0x158),	/* flags: in, out, base type, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 228 (parameter pBuffer) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x40),	/* type offset = 64 */
/* 234 (procedure meathook_interface::GetSpawnInfo) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x41,
        0x02,	/* 2 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 260 (parameter Size) */
        NdrFcShort(0x158),	/* flags: in, out, base type, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 266 (parameter pBuffer) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x52),	/* type offset = 82 */
/* 272 (procedure meathook_interface::KeepAlive) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0x8),	/* stack size = 8 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x40,
        0x01,	/* 1 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 298 (parameter Size) */
        NdrFcShort(0x158),	/* flags: in, out, base type, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 304 (procedure meathook_interface::GetAPRuntimeInfo) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x8),	/* method 8 */
        NdrFcShort(0x8),	/* stack size = 8 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x0),	/* server buffer = 0 */
        0x41,
        0x01,	/* 1 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 330 (parameter info) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x76),	/* type offset = 118 */
/* 336 (procedure meathook_interface::GetRuntimeSnapshot) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x9),	/* method 9 */
        NdrFcShort(0x8),	/* stack size = 8 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x0),	/* server buffer = 0 */
        0x41,
        0x01,	/* 1 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 362 (parameter snapshot) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0xa8),	/* type offset = 168 */
/* 368 (procedure meathook_interface::ApplyDeathLink) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xa),	/* method 10 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x6),	/* server buffer = 6 */
        0x42,
        0x02,	/* 2 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 394 (parameter request_id) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0xce),	/* type offset = 206 */
/* 400 (parameter status) */
        NdrFcShort(0x2010),	/* flags: out, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xd2),	/* type offset = 210 */
/* 406 (procedure meathook_interface::GetAPEventsSince) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xb),	/* method 11 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x0),	/* server buffer = 0 */
        0x41,
        0x03,	/* 3 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 432 (parameter after_sequence) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x0b,	/* FC_HYPER */
        0x0,
/* 438 (parameter max_count) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 444 (parameter batch) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0xfe),	/* type offset = 254 */
/* 450 (procedure meathook_interface::GetInventoryItemCount) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xc),	/* method 12 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x0),	/* server buffer = 0 */
        0x43,
        0x02,	/* 2 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 476 (parameter decl_name) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x116),	/* type offset = 278 */
/* 482 (parameter result) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x120),	/* type offset = 288 */
/* 488 (procedure meathook_interface::HasPlayerPerk) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xd),	/* method 13 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x0),	/* server buffer = 0 */
        0x43,
        0x02,	/* 2 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 514 (parameter decl_name) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x136),	/* type offset = 310 */
/* 520 (parameter result) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x140),	/* type offset = 320 */
/* 526 (procedure meathook_interface::IsPlayerPerkActive) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xe),	/* method 14 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x0),	/* server buffer = 0 */
        0x43,
        0x02,	/* 2 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 552 (parameter decl_name) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x156),	/* type offset = 342 */
/* 558 (parameter result) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x140),	/* type offset = 320 */
/* 564 (procedure meathook_interface::GetEquippedWeapon) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xf),	/* method 15 */
        NdrFcShort(0x8),	/* stack size = 8 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x0),	/* server buffer = 0 */
        0x41,
        0x01,	/* 1 params */
        0x0a,
        0x00,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 590 (parameter result) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x16a),	/* type offset = 362 */
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (unsigned char *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/*  4 */
        0x22,	/* FC_C_CSTRING */
        0x5c,	/* FC_PAD */
/* 6 (char *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/*  8 */
        0x22,	/* FC_C_CSTRING */
        0x5c,	/* FC_PAD */
/* 10 (char *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x28,	/* Corr desc: parameter Size, FC_LONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 20 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff4),	/* Offset= -12 (10) */
/* 24 (int *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 28 (unsigned char *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x28,	/* Corr desc: parameter Size, FC_LONG */
        0x54,	/* FC_DEREFERENCE */
        NdrFcShort(0x0),	/* offset = 0 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 38 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff4),	/* Offset= -12 (28) */
/* 42 (int *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 46 (unsigned char *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x28,	/* Corr desc: parameter Size, FC_LONG */
        0x54,	/* FC_DEREFERENCE */
        NdrFcShort(0x0),	/* offset = 0 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 56 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff4),	/* Offset= -12 (46) */
/* 60 (int *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 64 (unsigned char *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x28,	/* Corr desc: parameter Size, FC_LONG */
        0x54,	/* FC_DEREFERENCE */
        NdrFcShort(0x0),	/* offset = 0 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 74 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff4),	/* Offset= -12 (64) */
/* 78 (int *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 82 (unsigned char *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x28,	/* Corr desc: parameter Size, FC_LONG */
        0x54,	/* FC_DEREFERENCE */
        NdrFcShort(0x0),	/* offset = 0 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 92 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff4),	/* Offset= -12 (82) */
/* 96 (int *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 100 (char[32]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x20),	/* 32 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 106 (char[32]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x20),	/* 32 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 112 (char[64]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x40),	/* 64 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 118 (APRuntimeInfo) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x90),	/* 144 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (124) */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe4),	/* Offset= -28 (100) */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe6),	/* Offset= -26 (106) */
        0x08,	/* FC_LONG */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe7),	/* Offset= -25 (112) */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x3e,	/* FC_STRUCTPAD2 */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 152 (APRuntimeInfo *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffdc),	/* Offset= -36 (118) */
/* 156 (char[128]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x80),	/* 128 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 162 (char[128]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x80),	/* 128 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 168 (APRuntimeSnapshot) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x128),	/* 296 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (174) */
        0x0b,	/* FC_HYPER */
        0x0b,	/* FC_HYPER */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x38,	/* FC_ALIGNM4 */
        0x0a,	/* FC_FLOAT */
        0x0a,	/* FC_FLOAT */
        0x0d,	/* FC_ENUM16 */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffdc),	/* Offset= -36 (156) */
        0x02,	/* FC_CHAR */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffdd),	/* Offset= -35 (162) */
        0x3d,	/* FC_STRUCTPAD1 */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 202 (APRuntimeSnapshot *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffdc),	/* Offset= -36 (168) */
/* 206 */
        0x26,	/* FC_CSTRING */
        0x5c,	/* FC_PAD */
        NdrFcShort(0x40),	/* 64 */
/* 210 (APDeathLinkStatus *) */
        0x11, 0xc,	/* FC_RP [allocated_on_stack] [simple_pointer] */
        0x0d,	/* FC_ENUM16 */
        0x5c,	/* FC_PAD */
/* 214 (char[64]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x40),	/* 64 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 220 (APEvent) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x50),	/* 80 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (226) */
        0x0b,	/* FC_HYPER */
        0x0d,	/* FC_ENUM16 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffee),	/* Offset= -18 (214) */
        0x40,	/* FC_STRUCTPAD4 */
        0x5b,	/* FC_END */
/* 236 (APEvent[128]) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x7,	/* 7 */
        NdrFcShort(0x80),	/* 128 */
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcLong(0xffffffff),	/* -1 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe2),	/* Offset= -30 (220) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 254 (APEventBatch) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x2820),	/* 10272 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (260) */
        0x08,	/* FC_LONG */
        0x39,	/* FC_ALIGNM8 */
        0x0b,	/* FC_HYPER */
        0x0b,	/* FC_HYPER */
        0x02,	/* FC_CHAR */
        0x39,	/* FC_ALIGNM8 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffde),	/* Offset= -34 (236) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 274 (APEventBatch *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffea),	/* Offset= -22 (254) */
/* 278 */
        0x26,	/* FC_CSTRING */
        0x5c,	/* FC_PAD */
        NdrFcShort(0x80),	/* 128 */
/* 282 (char[128]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x80),	/* 128 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 288 (APInventoryIntResult) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8c),	/* 140 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (294) */
        0x0d,	/* FC_ENUM16 */
        0x02,	/* FC_CHAR */
        0x38,	/* FC_ALIGNM4 */
        0x08,	/* FC_LONG */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffec),	/* Offset= -20 (282) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 306 (APInventoryIntResult *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffec),	/* Offset= -20 (288) */
/* 310 */
        0x26,	/* FC_CSTRING */
        0x5c,	/* FC_PAD */
        NdrFcShort(0x80),	/* 128 */
/* 314 (char[128]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x80),	/* 128 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 320 (APInventoryBoolResult) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x1,	/* 1 */
        NdrFcShort(0x88),	/* 136 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (326) */
        0x0d,	/* FC_ENUM16 */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffed),	/* Offset= -19 (314) */
        0x3e,	/* FC_STRUCTPAD2 */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 338 (APInventoryBoolResult *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffec),	/* Offset= -20 (320) */
/* 342 */
        0x26,	/* FC_CSTRING */
        0x5c,	/* FC_PAD */
        NdrFcShort(0x80),	/* 128 */
/* 346 (APInventoryBoolResult *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffe4),	/* Offset= -28 (320) */
/* 350 (char[128]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x80),	/* 128 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 356 (char[128]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x80),	/* 128 */
        0x02,	/* FC_CHAR */
        0x5b,	/* FC_END */
/* 362 (APEquippedWeaponResult) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x1,	/* 1 */
        NdrFcShort(0x108),	/* 264 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (368) */
        0x0d,	/* FC_ENUM16 */
        0x02,	/* FC_CHAR */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe8),	/* Offset= -24 (350) */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffea),	/* Offset= -22 (356) */
        0x3f,	/* FC_STRUCTPAD3 */
        0x5b,	/* FC_END */
/* 382 (APEquippedWeaponResult *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffea),	/* Offset= -22 (362) */
        0x0
    }
};

