/*** Autogenerated by WIDL 6.0.3 from RPCInterface/meathook_interface.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __meathook_interface_h__
#define __meathook_interface_h__

/* Forward declarations */

/* Headers for imported files */


#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * meathook_interface interface (v1.0)
 */
#ifndef __meathook_interface_INTERFACE_DEFINED__
#define __meathook_interface_INTERFACE_DEFINED__

extern handle_t meathook_interface__MIDL_AutoBindHandle;
extern RPC_IF_HANDLE meathook_interface_v1_0_c_ifspec;
extern RPC_IF_HANDLE meathook_interface_v1_0_s_ifspec;
void __cdecl ExecuteConsoleCommand(
    unsigned char *pszString);

void __cdecl PushEntitiesFile(
    char *pBuffer,
    boolean Start,
    int Size);

void __cdecl UploadData(
    int Size,
    int Offset,
    char *pBuffer);

void __cdecl GetEntitiesFile(
    int *Size,
    unsigned char *pBuffer);

void __cdecl GetActiveEncounter(
    int *Size,
    unsigned char *pBuffer);

void __cdecl GetCurrentCheckpoint(
    int *Size,
    unsigned char *pBuffer);

void __cdecl GetSpawnInfo(
    int *Size,
    unsigned char *pBuffer);

void __cdecl KeepAlive(
    int *Size);

#define MH_AP_PROTOCOL_VERSION (9)

#define MEATHOOK_INTERFACE_AP_RUNTIME_TYPES_DEFINED
typedef enum APGameState {
    AP_GAME_STATE_UNKNOWN = 0,
    AP_GAME_STATE_MAIN_MENU = 1,
    AP_GAME_STATE_LOADING = 2,
    AP_GAME_STATE_GAMEPLAY = 3,
    AP_GAME_STATE_PAUSED = 4
} APGameState;
typedef struct APRuntimeInfo {
    char runtime_name[32];
    char runtime_version[32];
    ULONG protocol_version;
    char game_build[64];
    boolean build_supported;
    boolean hooks_ready;
    boolean capability_runtime_snapshot;
    boolean capability_map;
    boolean capability_game_state;
    boolean capability_checkpoint;
    boolean capability_native_deathlink;
    boolean capability_native_events;
    boolean capability_extra_life_telemetry;
    boolean capability_inventory_read;
} APRuntimeInfo;
typedef struct APRuntimeSnapshot {
    hyper sequence;
    hyper timestamp;
    boolean runtime_ready;
    boolean player_valid;
    boolean dead_valid;
    boolean dead;
    boolean health_valid;
    boolean max_health_valid;
    float health;
    float max_health;
    APGameState game_state;
    boolean game_state_valid;
    boolean map_valid;
    char map[128];
    boolean checkpoint_valid;
    char checkpoint[128];
} APRuntimeSnapshot;
void __cdecl GetAPRuntimeInfo(
    APRuntimeInfo *info);

void __cdecl GetRuntimeSnapshot(
    APRuntimeSnapshot *snapshot);

typedef enum APDeathLinkStatus {
    AP_DEATHLINK_QUEUED = 0,
    AP_DEATHLINK_INVOKED = 1,
    AP_DEATHLINK_UNAVAILABLE = 2,
    AP_DEATHLINK_INVALID_PLAYER = 3,
    AP_DEATHLINK_UNSUPPORTED = 4,
    AP_DEATHLINK_ERROR = 5,
    AP_DEATHLINK_INVALID = 6
} APDeathLinkStatus;
typedef enum APEventType {
    AP_EVENT_PLAYER_DEAD = 1,
    AP_EVENT_PLAYER_RESPAWNED = 2,
    AP_EVENT_DEATHLINK_INVOKED = 3
} APEventType;
typedef struct APEvent {
    hyper sequence;
    APEventType type;
    char request_id[64];
} APEvent;
typedef struct APEventBatch {
    ULONG count;
    hyper latest_sequence;
    hyper oldest_sequence;
    boolean gap;
    APEvent events[128];
} APEventBatch;
void __cdecl ApplyDeathLink(
    char request_id[64],
    APDeathLinkStatus *status);

void __cdecl GetAPEventsSince(
    hyper after_sequence,
    ULONG max_count,
    APEventBatch *batch);

typedef enum APInventoryStatus {
    AP_INVENTORY_QUEUED = 0,
    AP_INVENTORY_OK = 1,
    AP_INVENTORY_UNSUPPORTED = 2,
    AP_INVENTORY_INVALID_ARGUMENT = 3,
    AP_INVENTORY_INVALID_PLAYER = 4,
    AP_INVENTORY_ERROR = 5
} APInventoryStatus;
typedef struct APInventoryIntResult {
    APInventoryStatus status;
    boolean valid;
    LONG value;
    char diagnostic[128];
} APInventoryIntResult;
typedef struct APInventoryBoolResult {
    APInventoryStatus status;
    boolean valid;
    boolean value;
    char diagnostic[128];
} APInventoryBoolResult;
typedef struct APEquippedWeaponResult {
    APInventoryStatus status;
    boolean valid;
    char value[128];
    char diagnostic[128];
} APEquippedWeaponResult;
void __cdecl GetInventoryItemCount(
    char decl_name[128],
    APInventoryIntResult *result);

void __cdecl HasPlayerPerk(
    char decl_name[128],
    APInventoryBoolResult *result);

void __cdecl IsPlayerPerkActive(
    char decl_name[128],
    APInventoryBoolResult *result);

void __cdecl GetEquippedWeapon(
    APEquippedWeaponResult *result);


#endif  /* __meathook_interface_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __meathook_interface_h__ */
