set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES MH_MSVC_ROOT MH_WINSDK_ROOT MH_WINSDK_VERSION)

if(NOT DEFINED MH_MSVC_ROOT OR MH_MSVC_ROOT STREQUAL "")
  message(FATAL_ERROR "MH_MSVC_ROOT is required; set it to the exact MSVC tool root containing include/ and lib/x64/")
endif()
if(NOT DEFINED MH_WINSDK_ROOT OR MH_WINSDK_ROOT STREQUAL "")
  message(FATAL_ERROR "MH_WINSDK_ROOT is required; set it to the exact Windows SDK root containing Include/ and Lib/")
endif()
if(NOT DEFINED MH_WINSDK_VERSION OR MH_WINSDK_VERSION STREQUAL "")
  message(FATAL_ERROR "MH_WINSDK_VERSION is required; set it to one exact SDK version directory")
endif()

set(MH_MSVC_INCLUDE "${MH_MSVC_ROOT}/include")
set(MH_MSVC_LIB "${MH_MSVC_ROOT}/lib/x64")
set(MH_WINSDK_INCLUDE "${MH_WINSDK_ROOT}/Include/${MH_WINSDK_VERSION}")
set(MH_WINSDK_LIB "${MH_WINSDK_ROOT}/Lib/${MH_WINSDK_VERSION}")
set(MH_REQUIRED_INCLUDE_DIRS
  "${MH_MSVC_INCLUDE}"
  "${MH_WINSDK_INCLUDE}/ucrt"
  "${MH_WINSDK_INCLUDE}/shared"
  "${MH_WINSDK_INCLUDE}/um")
set(MH_REQUIRED_LIB_DIRS
  "${MH_MSVC_LIB}"
  "${MH_WINSDK_LIB}/ucrt/x64"
  "${MH_WINSDK_LIB}/um/x64")

foreach(dir IN LISTS MH_REQUIRED_INCLUDE_DIRS)
  if(NOT IS_DIRECTORY "${dir}")
    message(FATAL_ERROR "Required Windows include directory missing: ${dir}; check MH_MSVC_ROOT/MH_WINSDK_ROOT/MH_WINSDK_VERSION")
  endif()
endforeach()
foreach(dir IN LISTS MH_REQUIRED_LIB_DIRS)
  if(NOT IS_DIRECTORY "${dir}")
    message(FATAL_ERROR "Required Windows x64 library directory missing: ${dir}; check MH_MSVC_ROOT/MH_WINSDK_ROOT/MH_WINSDK_VERSION")
  endif()
endforeach()

find_program(MH_CLANG clang)
find_program(MH_CLANGXX clang++)
find_program(MH_LLD_LINK lld-link)
find_program(MH_LLVM_AR NAMES llvm-ar llvm-ar-14)
find_program(MH_LLVM_ML NAMES llvm-ml llvm-ml-14)
find_program(MH_LLVM_RC NAMES llvm-rc llvm-rc-14)
if(NOT MH_CLANG OR NOT MH_CLANGXX OR NOT MH_LLD_LINK OR NOT MH_LLVM_AR)
  message(FATAL_ERROR "Required LLVM tools missing: clang, clang++, lld-link, and llvm-ar are required for x86_64-pc-windows-msvc")
endif()
if(NOT MH_LLVM_ML)
  message(FATAL_ERROR "MASM sources are present; llvm-ml or llvm-ml-14 is required to assemble snaphak_algo/*.asm")
endif()
if(MH_LLVM_RC)
  set(CMAKE_RC_COMPILER "${MH_LLVM_RC}" CACHE FILEPATH "LLVM resource compiler" FORCE)
else()
  set(MH_NO_RESOURCE_COMPILER "${CMAKE_CURRENT_LIST_DIR}/no_resource_compiler.sh")
  set(CMAKE_RC_COMPILER "${MH_NO_RESOURCE_COMPILER}" CACHE FILEPATH "Fail-closed resource compiler sentinel" FORCE)
  message(STATUS "No llvm-rc or llvm-rc-14 found; current source inventory has no .rc sources; resource compilation is fail-closed")
endif()

set(CMAKE_C_COMPILER "${MH_CLANG}" CACHE FILEPATH "Clang C compiler" FORCE)
set(CMAKE_CXX_COMPILER "${MH_CLANGXX}" CACHE FILEPATH "Clang C++ compiler" FORCE)
set(CMAKE_AR "${MH_LLVM_AR}" CACHE FILEPATH "LLVM archiver" FORCE)
set(CMAKE_C_COMPILER_TARGET x86_64-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-windows-msvc)
set(CMAKE_C_FLAGS_INIT "-target x86_64-pc-windows-msvc -fms-compatibility -fms-extensions")
set(CMAKE_CXX_FLAGS_INIT "-target x86_64-pc-windows-msvc -fms-compatibility -fms-extensions")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld-link")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld-link")
set(CMAKE_STATIC_LINKER_FLAGS_INIT "")

set(MH_WINDOWS_INCLUDE_DIRS "${MH_REQUIRED_INCLUDE_DIRS}" CACHE INTERNAL "Validated Windows include directories")
set(MH_WINDOWS_LIB_DIRS "${MH_REQUIRED_LIB_DIRS}" CACHE INTERNAL "Validated Windows x64 library directories")
include_directories(SYSTEM ${MH_WINDOWS_INCLUDE_DIRS})
link_directories(${MH_WINDOWS_LIB_DIRS})
